# Create environment: conda env create --file environment.yml
# Activate environment: conda activate brunel
# Deactivate environment: conda deactivate
# To remove environment: conda remove --name brunel --all
# To verify that the environment was removed: conda info --envs

name: brunel
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - seaborn
  - jupyter
  - cython
  - pytest
  - autopep8
  - isort
  - yapf
  - h5py
  #- mpi4py
  - scikit-learn
  - pytorch
  - tensorboard
  - torchvision
  - nest-simulator
  #- nest-simulator=*=mpi_openmpi*
  - lfpy
  - pip:
    - pytest
    - neo
    - elephant
    - quantities
    - viziphant
    - pydot
    - efel
